language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy
  - pypy3
install:
  - pip install -e .
  - pip list
script:
  - python pep8.py --testsuite testsuite
  - python pep8.py --statistics pep8.py
  - python pep8.py --doctest
  - python setup.py test

notifications:
  email:
    - IanLee1521@gmail.com
  irc:
    channels:
      - "irc.freenode.org##python-code-quality"
    use_notice: true
    skip_join: true
